[NETBEANS-54] Module Review Apache License testng.ant
emilianbold/incubator-netbeans pull request #238
Opened 2017-10-06 15:11 UTC by trevlewis

For issue https://github.com/emilianbold/incubator-netbeans/issues/199

Update old Oracle license to Apache License.

2017-10-07 09:52 UTC, emilianbold requested changes

2017-10-07 09:52 UTC, emilianbold commented on testng.ant/src/org/netbeans/modules/testng/ant/Bundle.properties
> +#
whitespace?

2017-10-09 18:22 UTC, trevlewis commented
@emilianbold Fixed whitespace.

2017-10-10 08:07 UTC, emilianbold approved these changes

2017-10-10 08:18 UTC, merged