[NETBEANS-54] Module Review versioning
emilianbold/incubator-netbeans pull request #239
Opened 2017-10-06 15:25 UTC by trevlewis

Fix #207

Update old Oracle license to Apache License.

2017-10-07 06:20 UTC, emilianbold requested changes

2017-10-07 06:20 UTC, emilianbold commented on versioning/apichanges.xml
> +
Don't change whitespace.

2017-10-07 06:20 UTC, emilianbold commented on versioning/apichanges.xml
> +
Doesn't look like the other xml headers (indenting, etc.) Just copy-paste from somewhere existing.

2017-10-07 06:20 UTC, emilianbold commented on versioning/apichanges.xml
> +                New method <code>VCSHistoryProvider.HistoryEntry.getParent()</code> to provide the
More space at the end.

2017-10-07 06:20 UTC, emilianbold commented on versioning/apichanges.xml
> +
Whitespace.

2017-10-09 16:54 UTC, trevlewis commented
The license for versioning/apichanges.xml was added by another PR.

2017-10-09 17:34 UTC, emilianbold approved these changes

2017-10-09 17:44 UTC, emilianbold commented
Could you fix the conflict? Looks good otherwise.

2017-10-09 18:01 UTC, trevlewis commented
@emilianbold Good to go now.

2017-10-09 18:19 UTC, merged