[NETBEANS-54] Module Review css.prep
emilianbold/incubator-netbeans pull request #272
Opened 2017-10-07 12:37 UTC by tomazst

Apache license added. Close #34

2017-10-08 01:20 UTC, junichi11 commented
Thanks for your help.

*.less and *.sass files don't support the `<#-- -->` comment. Then, CPWhereUsedQueryPluginTest fails if the license headers added to test data.(Because tests depend on offsets.) I don't know about qa-functional tests.

@emilianbold add `css.prep/test/unit/data/**` and `css.prep/test/qa-functional/data/**` to rat excludes?

2017-10-08 07:42 UTC, tomazst commented
The extension is *.less and *.scss. But actually is a freemarker file.

2017-10-08 08:55 UTC, junichi11 commented
I'm sorry I did not make it clear enough. Of course, template files are OK.
i.e. the following files are OK:
- css.prep/src/org/netbeans/modules/css/prep/ui/resources/style.less
- css.prep/src/org/netbeans/modules/css/prep/ui/resources/style.scss

But test files are not templates. Then, as I wrote above, unit tests fail if the license header is added to unit test file(e.g. css.prep/test/unit/data/testProject/public_html/lib1.scss). So, they should be added to rat excludes or unit tests must also be fixed.

2017-10-09 08:18 UTC, tomazst commented
I changed headers in unit folder in to /* */.

2017-10-11 18:24 UTC, emilianbold requested changes
It might be better to just exclude from Rat in build.xml the test files. They don't seem to be very complex at all, so there is nothing much to expressly protect.

2017-10-11 18:24 UTC, emilianbold commented on css.prep/test/qa-functional/data/css_prep/public_html/cc.less
> +<#--
I suspect this .less file does not support  `<#` comments

2017-10-11 18:24 UTC, emilianbold commented on css.prep/test/qa-functional/data/css_prep/public_html/cc.scss
> +<#--
Same for this .scss file.

2017-10-12 08:49 UTC, tomazst commented
Closed by mistake

2017-10-12 09:18 UTC, closed without merging

2017-10-12 10:57 UTC, tomazst commented
I created new pull request #314