[NETBEANS-54] Module Review ant.freeform
emilianbold/incubator-netbeans pull request #279
Opened 2017-10-07 18:53 UTC by bjansen

This PR fixes #4

2017-10-08 07:22 UTC, geertjanw commented
Looks good to me.

2017-10-11 13:37 UTC, emilianbold requested changes

2017-10-11 13:37 UTC, emilianbold commented on ant.freeform/test/unit/data/example-projects/extbuildroot/build/built.file
> +with the License.  You may obtain a copy of the License at
I would exclude this file...

2017-10-11 13:37 UTC, emilianbold commented on ant.freeform/test/unit/data/example-projects/simple/src/org/foo/myapp/some-resource.txt
> +  http://www.apache.org/licenses/LICENSE-2.0
I would also exclude this file, it's supposed to be an example.

2017-10-27 08:07 UTC, closed without merging