license header removed
emilianbold/incubator-netbeans pull request #3
Opened 2017-10-06 07:42 UTC by gravitydestroyer

CodeTemplates.xml did not have any license header.
License header from the rest two files has been removed. :)

2017-10-06 09:07 UTC, emilianbold commented
You don't have to remove, but replace them with the Apache license.

For XML files, copy-paste a license header from another XML file, for example: https://github.com/emilianbold/incubator-netbeans/blob/master/xml.jaxb/build.xml

For .properties file, copy-paste a license header from another .properties file, for example:
https://github.com/emilianbold/incubator-netbeans/blob/master/xml.jaxb/src/org/netbeans/modules/xml/jaxb/Bundle.properties

2017-10-06 09:08 UTC, emilianbold commented
Also, your commit message must be "[NETBEANS-54] Module Review xml.jaxb"

2017-10-06 10:29 UTC, emilianbold commented on xml.jaxb/src/org/netbeans/modules/xml/jaxb/layer.xml
> +      http://www.apache.org/licenses/LICENSE-2.0
Compared with the header here https://github.com/emilianbold/incubator-netbeans/blob/master/xml.jaxb/build.xml you are missing some new lines. Just copy-paste the license header, don't reformat it.

2017-10-06 12:07 UTC, emilianbold commented
BTW, note https://github.com/emilianbold/incubator-netbeans/issues/219 which was auto-generated afterwards and mentions some test files too.

2017-10-06 12:08 UTC, emilianbold requested changes

2017-10-06 12:08 UTC, emilianbold commented on xml.jaxb/src/org/netbeans/modules/xml/jaxb/layer.xml
> -<!DOCTYPE filesystem PUBLIC "-//NetBeans//DTD Filesystem 1.2//EN" "http://www.netbeans.org/dtds/filesystem-1_2.dtd">
This seems to move the DOCTYPE.

2017-10-06 12:08 UTC, emilianbold commented on xml.jaxb/src/org/netbeans/modules/xml/jaxb/ui/Bundle.properties
> +
This seems to have a extra empty line.

2017-10-08 21:49 UTC, emilianbold commented
@gravitydestroyer let me know if you still are working on this.

2017-10-12 13:55 UTC, emilianbold commented
@gravitydestroyer if I don't get a reply this week I'm going to assume you abandoned the issue.

2017-10-12 19:01 UTC, gravitydestroyer commented
@emilianbold checkout my latest commit.Sorry for the inconvenience.

2017-10-15 10:04 UTC, emilianbold requested changes
I see layer.xml was already modified upstream to have the license header so you don't have to do anything (please revert your change).

Only xml.jaxb/src/org/netbeans/modules/xml/jaxb/ui/Bundle.properties needs to be updated apparently.

2017-10-25 22:09 UTC, emilianbold commented
@gravitydestroyer you are almost done! Just undo you change in xml.jaxb/src/org/netbeans/modules/xml/jaxb/layer.xml.

Do you need any help?

2017-11-01 06:01 UTC, emilianbold commented
Hacktoberfest is over. Closing this PR. Feel free to reopen one for the issue, I will merge it if it's ok.

2017-11-01 06:01 UTC, closed without merging