[NETBEANS-54] Module Review
emilianbold/incubator-netbeans pull request #311
Opened 2017-10-10 22:15 UTC by bondolo

Switches HtmlElements.java to use ASF license.

Addresses #67

2017-10-11 03:58 UTC, emilianbold requested changes
You must also exclude in nbbuild/build.xml ("rat" task) the test data from html.lexer/test/unit/data/testfiles/**

2017-10-11 03:58 UTC, emilianbold commented on html.lexer/src/org/netbeans/lib/html/lexer/HtmlElements.java
> +
This extra new line is not necessary.

2017-10-16 20:27 UTC, bondolo commented
Should automatically resolve when you pull from apache repo

2017-10-18 05:04 UTC, emilianbold requested changes
I cannot review this since you did a bad rebase or something and I see 655 files changed.

A lot of commits appear as 'committed with Mike Duigou' which is a sign of rebase to me.

Please do a proper merge / rebase and push the new changes.

2017-10-22 06:42 UTC, emilianbold commented
Closing this since you opened https://github.com/emilianbold/incubator-netbeans/pull/327

2017-10-22 06:42 UTC, closed without merging